# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Input has to be provided for the workflow to run
        required: false        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  GetandCheckoutLatestVersion:    
    runs-on: ubuntu-latest       
    steps:
      - id: hyperhdrver
        name: Get HyperHDR latest version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: awawa-dev/HyperHDR
      - id: checkoutcode
        name: Checkout Code from remote repo
        uses: actions/checkout@v4.11
        with:
          repository: awawa-dev/HyperHDR
          ref: ${{ steps.hyperhdrver.outputs.release }}
          path: hyperhdr
          show-progress: true
          github-server-url: 'https://github.com'
    
    
  
