# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  GetandCheckoutLatestVersion:    
    runs-on: ubuntu-latest       
    steps:
      - id: hyperhdrver
        name: Get HyperHDR latest version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: awawa-dev/HyperHDR          
      - id: setHDHDRvar
        env:
          HYPERHDR_VER: ${{ steps.hyperhdrver.outputs.release }}
        run: echo $HYPERHDR_VER
      - id: checkoutcode
        name: Checkout Code from remote repo
        uses: actions/checkout@v4.1.1
        with:
          repository: awawa-dev/HyperHDR
          ref: $HYPERHDR_VER          
          show-progress: true
          github-server-url: 'https://github.com'
  BuildDebPackage:
    runs-on: ubuntu-latest
    steps: 
      - name: build-deb-action
        uses: jiro4989/build-deb-action@v3.0.0 
        with:
          package: HyperHDR
          package_root: ${GITHUB_WORKSPACE}
          maintainer: 'Jon Simcina'
          version: $HYPERHDR_VER
          arch: 'amd64'
        
        
            
    
  
