# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Input has to be provided for the workflow to run
        required: false        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  GetLatestVersion:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest   

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: hyperhdrver
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: awawa-dev/HyperHDR

      - id: ouput
        run: |
          ::warning "${{ steps.hyperhdrver.outputs.release }}"            
    
